https://raw.githubusercontent.com/markziemann/SLE712_files/master/bioinfo_asst3_part1_files/gene_expression.tsv
download.file("https://raw.githubusercontent.com/markziemann/SLE712_files/master/bioinfo_asst3_part1_files/gene_expression.tsv",
              destfile = "gene_expression.tsv")
x <- read.table("gene_expression.tsv")
head(x)
str(x)
x <- read.table("gene_expression",header=TRUE)
head(x)
str(x)
x <- read.table("gene_expression", header = TRUE, row.names = 1)
head(x)
str(x)
x <- read.table("gene_expression.tsv", header = TRUE , stringsAsFactors = FALSE )
head(x)
str(x)
x <- read.csv("gene_expression.tsv", sep="\t")
head(x)
str(x)
x <- read.csv("gene_expression.tsv", sep="\t",stringsAsFactors = FALSE)
head(x)