download.file("https://github.com/markziemann/SLE712_files/blob/master/bioinfo_asst3_part1_files/growth_data.csv",destfile = "gene expression.tsv")
x <- read.table("growthdata.csv")
head(x)
str(x)
x <- read.table("growthdata.csv", header = TRUE)
head(x)
str(x)
x <- read.table("growthdata.csv", header = TRUE, stringsAsFactors = FALSE )
head(x)
str(x)
x <- read.table("growthdata.csv", header = TRUE, stringsAsFactors = FALSE , row.names = 1 )
head(x)
str(x)
x <- read.csv("growthdata.csv" ,sep = "\t" ,stringsAsFactors = FALSE, row.names = 1)
head(x)
str(x)
