download.file("https://github.com/markziemann/SLE712_files/blob/master/bioinfo_asst3_part1_files
/growth_data.csv",destfile = "growth_data.csv")
x <- read.table("growth_data.csv")
head(x)
str(x)
x <- read.table("growth_data.csv",header=TRUE)
head(x)
str(x)
x <- read.table("growth_data.csv", header = TRUE, row.names = 1)
head(x)
str(x)
x <- read.table("growth_data.csv", header = TRUE , stringsAsFactors = FALSE )
head(x)
str(x)
x <- read.csv("growth_data.csv", sep="\t")
head(x)
str(x)
x <- read.csv("growth_data.csv", sep="\t",stringsAsFactors = FALSE)
head(x)
